name: coffee_cup
description: Biblioteca de componentes visuais do Mangá Easy.
version: 1.1.0
homepage: none
publish_to: none

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  themes:
    git: 
      url: https://github.com/manga-easy/manga_easy_themes.git
      ref: v1.1.0
  flutter_rating_bar: ^4.0.1
  flutter_cache_manager: ^3.3.0
  flutter_carousel_widget: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/features/assets/horn/
    - lib/features/assets/unicorn/
    - lib/features/assets/states/
    - lib/features/assets/cats/
